package com.mdeo.script.runtime
import com.mdeo.metamodel.Model

/**
 * Answers the calls a script makes to functions implemented outside the platform.
 *
 * The compiler emits, for every contributed signature with an external implementation, a stub
 * with the signature's own JVM descriptor. That stub boxes its arguments, calls [call], and
 * unboxes the result. Everything else — finding the session, encoding the arguments, applying
 * back whatever the service changed — lives behind this interface, so the generated bytecode
 * knows nothing about the transport and a test can stand in for it with a few lines.
 */
interface ExternalCallDispatcher {

    /**
     * Performs one external call.
     *
     * @param callId Identifies the signature being called. It matches
     *        [com.mdeo.script.compiler.ExternalCallSpec.callId] of exactly one compiled stub,
     *        which is where the operation name, the parameter types and the return type live.
     * @param arguments The call's arguments, boxed, in declaration order
     * @param model The model the script runs on, or null when it runs on none. Instances passed as
     *        arguments belong to it, and an operation that reads the model reads this one.
     * @return The result, boxed, or null for a signature that returns nothing
     */
    fun call(callId: String, arguments: Array<Any?>, model: Model?): Any?

    companion object {
        /**
         * The dispatcher a context uses when nothing installed one.
         *
         * A script that never calls an external function never touches it, so an execution path
         * that does not support them — a compiler test, a guidance function evaluated inside the
         * optimizer — keeps working unchanged. One that does call one fails with a message that
         * says what is missing rather than with a null pointer somewhere downstream.
         */
        val UNSUPPORTED: ExternalCallDispatcher = object : ExternalCallDispatcher {
            override fun call(callId: String, arguments: Array<Any?>, model: Model?): Any? {
                throw UnsupportedOperationException(
                    "External function '$callId' cannot be called here: this execution has no " +
                            "connection to the plugin that implements it"
                )
            }
        }
    }
}
