package com.mdeo.modeltransformation.runtime

import com.mdeo.expression.ast.expressions.TypedIdentifierExpression
import com.mdeo.expression.ast.expressions.TypedMemberAccessExpression
import com.mdeo.expression.ast.types.ClassTypeRef
import com.mdeo.expression.ast.types.ReturnType
import com.mdeo.expression.ast.types.VoidType
import com.mdeo.metamodel.Metamodel
import com.mdeo.metamodel.data.ClassData
import com.mdeo.metamodel.data.EnumData
import com.mdeo.metamodel.data.MetamodelData
import com.mdeo.metamodel.data.ModelData
import com.mdeo.metamodel.data.ModelDataInstance
import com.mdeo.metamodel.data.ModelDataLink
import com.mdeo.metamodel.data.ModelDataPropertyValue
import com.mdeo.metamodel.data.MultiplicityData
import com.mdeo.metamodel.data.PropertyData
import com.mdeo.modeltransformation.ast.TypedAst
import com.mdeo.modeltransformation.ast.patterns.TypedPattern
import com.mdeo.modeltransformation.ast.patterns.TypedPatternObjectInstance
import com.mdeo.modeltransformation.ast.patterns.TypedPatternObjectInstanceElement
import com.mdeo.modeltransformation.ast.patterns.TypedPatternPropertyAssignment
import com.mdeo.modeltransformation.ast.statements.TypedMatchStatement
import com.mdeo.modeltransformation.compiler.ExpressionCompilerRegistry
import com.mdeo.modeltransformation.graph.mdeo.MdeoModelGraph
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Integration tests validating enum handling in model transformations when using [MdeoModelGraph].
 *
 * ## Bug
 *
 * Two related failures occur when enums are used in model transformations backed by [MdeoModelGraph]:
 *
 * ### 1. ClassCastException on assignment
 *
 * When a transformation assigns an enum value (e.g. `status = OrderStatus.PENDING`), the
 * compiled expression resolves to the backtick-formatted string `` `OrderStatus`.`PENDING` ``.
 * [MdeoModelGraph] delegates property writes to the ASM-generated [com.mdeo.metamodel.ModelInstance]
 * via `setPropertyByKey`. The generated bytecode performs a `CHECKCAST` to the concrete enum
 * value class (`OrderStatusEnumValue`), so passing a raw `String` throws:
 *
 *     java.lang.ClassCastException: class java.lang.String cannot be cast to class
 *     com.mdeo.metamodel.generated.enum.OrderStatusEnumValueEnumValue
 *
 * ### 2. Equality comparison always fails
 *
 * When a match pattern tests `status == OrderStatus.PENDING`, the graph reads the property
 * value from the backing `ModelInstance`. Because the instance stores a concrete `EnumValue`
 * object (not a string), comparing it via Gremlin's `where(P.eq(...))` against the backtick
 * string always fails.
 *
 * ## Fix
 *
 * [com.mdeo.modeltransformation.graph.mdeo.MdeoVertex] now transparently converts:
 * - **on write**: backtick string → concrete enum value object (via [Metamodel.resolveEnumValue])
 * - **on read**: concrete enum value object → backtick string
 *
 * This keeps the representation consistent with [com.mdeo.modeltransformation.graph.tinker.TinkerModelGraph].
 */
class MdeoEnumTransformationTest {

    // -------------------------------------------------------------------------
    // Type index layout
    //   0 → void
    //   1 → builtin.string
    //   2 → builtin.double
    //   3 → builtin.boolean
    //   4 → Any (nullable)
    //   5 → enum.OrderStatus          (enum value type)
    //   6 → enum-container.OrderStatus (container type for the identifier "OrderStatus")
    // -------------------------------------------------------------------------
    private val types: List<ReturnType> = listOf(
        VoidType(),                                                                          // 0
        ClassTypeRef(`package` = "builtin", type = "string",         isNullable = false),   // 1
        ClassTypeRef(`package` = "builtin", type = "double",         isNullable = false),   // 2
        ClassTypeRef(`package` = "builtin", type = "boolean",        isNullable = false),   // 3
        ClassTypeRef(`package` = "builtin", type = "Any",            isNullable = true),    // 4
        ClassTypeRef(`package` = "enum",    type = "OrderStatus",    isNullable = false),   // 5
        ClassTypeRef(`package` = "enum-container", type = "OrderStatus", isNullable = false) // 6
    )

    private val metamodelData = MetamodelData(
        classes = listOf(
            ClassData(
                name = "Order",
                isAbstract = false,
                extends = emptyList(),
                properties = listOf(
                    PropertyData(
                        name = "status",
                        enumType = "OrderStatus",
                        multiplicity = MultiplicityData.single()
                    )
                )
            )
        ),
        enums = listOf(
            EnumData(
                name = "OrderStatus",
                entries = listOf("PENDING", "CONFIRMED", "SHIPPED")
            )
        )
    )

    private val metamodel = Metamodel.compile(metamodelData)

    /** Graph key for "Order.status" in the underlying graph. */
    private val statusKey: String = "prop_${metamodel.metadata.classes["Order"]!!.propertyFields["status"]!!.fieldIndex}"

    // =========================================================================
    // Helper: builds AST for `create o: Order { status = OrderStatus.PENDING }`
    // =========================================================================

    /**
     * Builds a [TypedAst] that creates a new `Order` vertex and sets
     * `status = OrderStatus.PENDING` using a [TypedMemberAccessExpression].
     *
     * @param scopeIndex The scope index for the `OrderStatus` identifier (1 = global scope).
     */
    private fun buildCreateAst(scopeIndex: Int = 1): TypedAst = TypedAst(
        types = types,
        metamodelPath = "",
        statements = listOf(
            TypedMatchStatement(
                pattern = TypedPattern(
                    elements = listOf(
                        TypedPatternObjectInstanceElement(
                            objectInstance = TypedPatternObjectInstance(
                                modifier = "create",
                                name = "o",
                                className = "Order",
                                properties = listOf(
                                    TypedPatternPropertyAssignment(
                                        propertyName = "status",
                                        operator = "=",
                                        value = TypedMemberAccessExpression(
                                            evalType = 5,   // enum.OrderStatus
                                            expression = TypedIdentifierExpression(
                                                evalType = 6, // enum-container.OrderStatus
                                                name = "OrderStatus",
                                                scope = scopeIndex
                                            ),
                                            member = "PENDING",
                                            isNullChaining = false
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )

    /**
     * Builds a [TypedAst] that matches an existing `Order` vertex where
     * `status == OrderStatus.CONFIRMED` and sets `status = OrderStatus.SHIPPED`.
     */
    private fun buildMatchAndAssignAst(): TypedAst = TypedAst(
        types = types,
        metamodelPath = "",
        statements = listOf(
            TypedMatchStatement(
                pattern = TypedPattern(
                    elements = listOf(
                        TypedPatternObjectInstanceElement(
                            objectInstance = TypedPatternObjectInstance(
                                modifier = "match",
                                name = "o",
                                className = "Order",
                                properties = listOf(
                                    // Match condition: status == OrderStatus.CONFIRMED
                                    TypedPatternPropertyAssignment(
                                        propertyName = "status",
                                        operator = "==",
                                        value = TypedMemberAccessExpression(
                                            evalType = 5,
                                            expression = TypedIdentifierExpression(
                                                evalType = 6,
                                                name = "OrderStatus",
                                                scope = 1
                                            ),
                                            member = "CONFIRMED",
                                            isNullChaining = false
                                        )
                                    )
                                )
                            )
                        ),
                        // Assignment in the same match block: o.status = OrderStatus.SHIPPED
                        TypedPatternObjectInstanceElement(
                            objectInstance = TypedPatternObjectInstance(
                                modifier = "match",
                                name = "o",
                                className = "Order",
                                properties = listOf(
                                    TypedPatternPropertyAssignment(
                                        propertyName = "status",
                                        operator = "=",
                                        value = TypedMemberAccessExpression(
                                            evalType = 5,
                                            expression = TypedIdentifierExpression(
                                                evalType = 6,
                                                name = "OrderStatus",
                                                scope = 1
                                            ),
                                            member = "SHIPPED",
                                            isNullChaining = false
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )

    // =========================================================================
    // Tests
    // =========================================================================

    /**
     * Verifies that a transformation can CREATE a new `Order` vertex and assign
     * an enum property via [MdeoModelGraph] without throwing a [ClassCastException].
     *
     * Before the fix `MdeoVertex.property(cardinality, key, value)` passed the
     * backtick string directly to `ModelInstance.setPropertyByKey`, which performed
     * a `CHECKCAST` to the generated enum class and threw:
     *
     *     java.lang.ClassCastException: class java.lang.String cannot be cast
     *     to class com.mdeo.metamodel.generated.enum.OrderStatusEnumValue
     *
     * After the fix, [MdeoVertex] converts the backtick string to the actual enum
     * object before writing, and converts it back when reading.
     */
    @Test
    fun `MdeoModelGraph - enum assignment in create block does not throw ClassCastException`() {
        val graph = MdeoModelGraph.create(
            ModelData(metamodelPath = "", instances = emptyList(), links = emptyList()),
            metamodel
        )

        val engine = TransformationEngine(
            modelGraph = graph,
            ast = buildCreateAst(),
            expressionCompilerRegistry = ExpressionCompilerRegistry.createDefaultRegistry(),
            statementExecutorRegistry = StatementExecutorRegistry.createDefaultRegistry()
        )

        val result = engine.execute()

        assertTrue(
            result is TransformationExecutionResult.Success,
            "Transformation should succeed but got: $result"
        )

        // Verify the vertex was created and its enum property reads back as the
        // correct backtick-formatted string (not as a raw EnumValue object)
        val g = graph.traversal()
        val orderVertices = g.V().hasLabel("Order").toList()
        assertEquals(1, orderVertices.size, "Exactly one Order vertex should have been created")

        val statusProp = orderVertices[0].property<String>(statusKey)
        assertTrue(statusProp.isPresent, "The 'status' property should be present on the created Order vertex")
        assertEquals(
            "`OrderStatus`.`PENDING`",
            statusProp.value(),
            "The 'status' property should read back as the backtick-formatted enum string"
        )

        graph.close()
    }

    /**
     * Verifies that a transformation can MATCH an existing `Order` vertex by its enum
     * property value using [MdeoModelGraph].
     *
     * Before the fix, the graph stored and returned the raw `EnumValue` object.
     * Gremlin's `where(P.eq(...))` compared it against the backtick string, which
     * always evaluated to `false`, so no vertex was ever matched.
     *
     * After the fix the read path converts the stored enum object back to the backtick
     * string, making the comparison work correctly.
     */
    @Test
    fun `MdeoModelGraph - enum equality comparison in match block correctly filters vertices`() {
        // Pre-populate graph: one CONFIRMED order, one PENDING order
        val modelData = ModelData(
            metamodelPath = "",
            instances = listOf(
                ModelDataInstance(
                    name = "order1",
                    className = "Order",
                    properties = mapOf(
                        "status" to ModelDataPropertyValue.EnumValue("CONFIRMED")
                    )
                ),
                ModelDataInstance(
                    name = "order2",
                    className = "Order",
                    properties = mapOf(
                        "status" to ModelDataPropertyValue.EnumValue("PENDING")
                    )
                )
            ),
            links = emptyList()
        )

        val graph = MdeoModelGraph.create(modelData, metamodel)

        val engine = TransformationEngine(
            modelGraph = graph,
            ast = buildMatchAndAssignAst(),
            expressionCompilerRegistry = ExpressionCompilerRegistry.createDefaultRegistry(),
            statementExecutorRegistry = StatementExecutorRegistry.createDefaultRegistry()
        )

        val result = engine.execute()

        assertTrue(
            result is TransformationExecutionResult.Success,
            "Transformation should succeed but got: $result"
        )

        val g = graph.traversal()
        val orderVertices = g.V().hasLabel("Order").toList()
        assertEquals(2, orderVertices.size, "Both Order vertices must still exist")

        // Collect statuses: the CONFIRMED one should now be SHIPPED
        val statuses = orderVertices
            .map { it.property<String>(statusKey).value() }
            .sorted()

        assertEquals(
            listOf("`OrderStatus`.`PENDING`", "`OrderStatus`.`SHIPPED`"),
            statuses,
            "The CONFIRMED order should have been matched and updated to SHIPPED; " +
            "the PENDING order should remain unchanged"
        )

        graph.close()
    }

    /**
     * Verifies that enum values written by one transformation (or loaded from model data) can
     * be read back as backtick-formatted strings via the Gremlin traversal API on [MdeoModelGraph].
     *
     * This ensures [MdeoVertex.property] returns consistent values whether the enum was:
     * - loaded from [ModelData] via [MdeoModelGraph.create], or
     * - written during a transformation.
     */
    @Test
    fun `MdeoModelGraph - enum values loaded from ModelData read back as backtick strings`() {
        val modelData = ModelData(
            metamodelPath = "",
            instances = listOf(
                ModelDataInstance(
                    name = "order1",
                    className = "Order",
                    properties = mapOf(
                        "status" to ModelDataPropertyValue.EnumValue("SHIPPED")
                    )
                )
            ),
            links = emptyList()
        )

        val graph = MdeoModelGraph.create(modelData, metamodel)
        val g = graph.traversal()

        val statusProp = g.V().hasLabel("Order").next().property<String>(statusKey)
        assertTrue(statusProp.isPresent, "status property should be present")
        assertEquals(
            "`OrderStatus`.`SHIPPED`",
            statusProp.value(),
            "Enum value loaded from ModelData should read back as backtick-formatted string"
        )

        // Also verify via values() traversal step (used by Gremlin filters)
        val statusValues = g.V().hasLabel("Order").values<String>(statusKey).toList()
        assertEquals(1, statusValues.size)
        assertEquals("`OrderStatus`.`SHIPPED`", statusValues[0])

        graph.close()
    }

    /**
     * Verifies that the backtick-string-to-enum-entry parsing logic is robust by testing
     * with all three enum entries in `OrderStatus` and ensuring round-trip consistency.
     */
    @Test
    fun `MdeoModelGraph - all enum entries survive write-read round trip`() {
        for (entry in listOf("PENDING", "CONFIRMED", "SHIPPED")) {
            val modelData = ModelData(
                metamodelPath = "",
                instances = listOf(
                    ModelDataInstance(
                        name = "o1",
                        className = "Order",
                        properties = mapOf(
                            "status" to ModelDataPropertyValue.EnumValue(entry)
                        )
                    )
                ),
                links = emptyList()
            )

            val graph = MdeoModelGraph.create(modelData, metamodel)
            val g = graph.traversal()

            val statusValue = g.V().hasLabel("Order").next().property<String>(statusKey).value()
            assertEquals(
                "`OrderStatus`.`$entry`",
                statusValue,
                "Entry '$entry' should round-trip correctly through MdeoModelGraph"
            )

            graph.close()
        }
    }
}
